workflows:
  android-release:
    name: "SLM Rapport Android Release"

    environment:
      java: 17

    scripts:
      - name: "Check Java and Gradle"
        script: |
          java -version
          chmod +x ./gradlew
          ./gradlew --version

      - name: "Clean project"
        script: |
          ./gradlew clean

      - name: "Build release APK"
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk

  android-debug:
    name: "SLM Rapport Debug APK"

    environment:
      java: 17

    scripts:
      - name: "Prepare Gradle"
        script: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: "Build debug APK"
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
